server:
    port: ${SERVER_PORT:8082}

app:
    database:
        host: ${DATABASE_HOST:localhost}
        port: ${DATABASE_PORT:5432}
        name: ${DATABASE_NAME:featureflag}
        username: ${DATABASE_USERNAME:featureflag_user}
        password: ${DATABASE_PASSWORD:featureflag_pass}

spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://${app.database.host}:${app.database.port}/${app.database.name}
        username: ${app.database.username}
        password: ${app.database.password}
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
        show-sql: false
    data:
        redis:
            host: ${REDIS_HOST:localhost}
            port: ${REDIS_PORT:6379}
